name: omni_for_pyload
description: "Your all-in-one mobile app for pyLoad."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  openapi_client:
      path: ./packages/openapi_client
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0
  get_it: ^9.0.5
  file_picker: ^10.3.7
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  permission_handler: ^12.0.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.0
  mockito: ^5.4.0
  flutter_launcher_icons: "^0.14.4"
  fake_async: ^1.3.3

flutter:
  uses-material-design: true
